version: '3.7'

services:
  vending_machine:
    container_name: vending_machine
    working_dir: /home/wwwroot/vending.machine
    build:
      target: dev
      context: .
      dockerfile: ./ops/docker/Dockerfile
    volumes:
      - .:/home/wwwroot/vending.machine
